trigger:
  branches:
    include: ["*"]
pool:
  vmImage: ubuntu-22.04
stages:
  - stage: Calidad
    jobs:
      - job: lint_and_test
        steps:
          - script: pip install detect-secrets hvac && .ci/scripts/detect_secrets.sh
            displayName: Detect secrets
          - script: pip install ruff sqlfluff && .ci/scripts/lint_dags.sh && .ci/scripts/lint_spark.sh && .ci/scripts/lint_sql.sh
            displayName: Lint all
          - script: pip install pytest pytest-cov hvac && .ci/scripts/test_dags.sh
            displayName: Test DAGs
          - script: pip install pytest pytest-cov chispa && .ci/scripts/test_spark.sh
            displayName: Test Spark
  - stage: Deploy_Staging
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    jobs:
      - deployment: staging
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - script: .ci/scripts/deploy_k3s.sh staging
  - stage: Deploy_Prod
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - deployment: production
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: .ci/scripts/deploy_k3s.sh prod
